// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const option: string;
export const selected: string;
export const hasDescription: string;
export const recommended: string;
export const recommendedBadge: string;
export const optionMain: string;
export const input: string;
export const label: string;
export const explainButton: string;
export const description: string;
export const options: string;
export const otherContainer: string;
