import { generateTypes } from './scripts/postcss-plugins/postcss-generate-types.mjs';

// eslint-disable-next-line n/no-process-env -- Workaround for `Malformed PostCSS Configuration` error while running `next build`
const isProduction = (process.env.NODE_ENV === 'production');

export default {
	plugins: [
		...(isProduction ? [] : [
			generateTypes({
				banner: '// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!'
			})
		])
	]
};
