// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const header: string;
export const title: string;
export const titleAccent: string;
export const description: string;
export const content: string;
export const commentsSection: string;
export const buttons: string;
export const validationHint: string;
export const poweredBy: string;
