// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const bold: string;
export const italic: string;
export const strikethrough: string;
export const code: string;
