// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const container: string;
export const card: string;
export const title: string;
export const subtitle: string;
